#!/bin/bash

LOGFILE='./tmpfsmysql.log'
LOGFILE_LINES=1000
CONFIG_FILE='tmpfsmysql.cfg'
MESSAGE_INSTALLING_MYSQL="Installing the new mysql database in the tmpfs directory..."
MESSAGE_STARTING_MYSQL="Starting the tmpfs mysql server with specific parameters in order to use the tmpfs datadir..."

SOCKET_FILE='/tmp/tmpfs-mysql/tmpfs-mysqld.sock'

echo -e "\nThe script needs sudo access in order to work"
sudo date >>$LOGFILE # dummy command to cache the sudo credentials for the commands below

function checkForMySQL {
	local MYSQLDINSTALLED=`sudo which mysqld 2>>$LOGFILE`
	if [ "$MYSQLDINSTALLED" == "" ]
	then
		echo ""
		echo "You don't seem to have MySQL server installed! Please install it before running this script."
		echo ""
		exit 0
	fi
}
checkForMySQL

MYSQL_VERSION_RAW=`sudo mysqld --version 2>>$LOGFILE`
SERVER_MODE='MySQL'

if [[ "$MYSQL_VERSION_RAW" == *"MariaDB"* ]]; then
	SERVER_MODE='MariaDB'
fi

MYSQL_VERSION_XX=`sudo mysqld --version 2>/dev/null | awk '{ print $3 }' | awk -F"." '{ print $1 $2 }' | awk -F"-" '{ print $1 }'`
MYSQL_VERSION_XXX=`sudo mysqld --version 2>/dev/null | awk '{ print $3 }' | awk -F"." '{ print $1 $2 $3 }' | awk -F"-" '{ print $1 }'`
MYSQL_VERSION_Xxx=`sudo mysqld --version 2>/dev/null | awk '{ print $3 }' | awk -F"." '{ print $1 }' | awk -F"-" '{ print $1 }'`
MYSQL_VERSION_xXx=`sudo mysqld --version 2>/dev/null | awk '{ print $3 }' | awk -F"." '{ print $2 }' | awk -F"-" '{ print $1 }'`
MYSQL_VERSION_xxX=`sudo mysqld --version 2>/dev/null | awk '{ print $3 }' | awk -F"." '{ print $3 }' | awk -F"-" '{ print $1 }'`

echo -ne "\nYou are using $SERVER_MODE version $MYSQL_VERSION_Xxx.$MYSQL_VERSION_xXx.$MYSQL_VERSION_xxX\n"

function LOAD_CONFIG
{
	if test -e "$CONFIG_FILE" -a -r "$CONFIG_FILE" -a -f "$CONFIG_FILE"
	then
		source "$CONFIG_FILE"
	else
		touch "$CONFIG_FILE"
		printf "# tmpfs filesystem size in MB, values below 256 are not recommended\n\
TMPFS_SIZE=256\n\
PORT=3344\n\
PASSWORD='drowssap'\n\

# additional parameters for the mysqld command
# sql-mode could be used to make MySQL 5.7 behave like MySQL 5.6
# see more here http://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_sql_mode
# --sql-mode=NO_ENGINE_SUBSTITUTION
MYSQLDPARAMS=''

DBNAMES[0]=''\n\
DUMPFILES[0]=''\n\
# import database, host:port:user:pass:dbname\n\
IMPORTSFROM[0]='::::'\n\
RUNCOMMANDS[0]=''\n" > "$CONFIG_FILE"
	source "$CONFIG_FILE"
	fi
}
LOAD_CONFIG


if [ "$1" == "" ]
then
	echo -ne "\E[1;29;42mTMPFS-MYSQL server management tool"
	tput sgr0
	echo -e "\n"
	echo "Available command options are:"
	echo " start     - Starts the tmpfs mysql instance. This will kill any already started tmpfs mysql server"
	echo " stop      - Stop the tmpfs mysql server instance"
	echo " kill      - Kill any other instances of the mysqld daemon besides the normal mysql server"
	echo " status    - Check whether the tmpfs mysql server is running"
	echo " client    - You will be connected to the tmpfs mysql server using the mysql client"
	echo " showdb    - Show a list of the databases on the tmpfs mysql server"
	echo " checkdump - Check if the dump file configured in DUMPFILE exists and is readable"
	echo -ne "\n"
	exit 0
fi

PID=`sudo cat /tmp/tmpfs-mysql/tmpfs-mysqld.pid 2>/dev/null`

function killByPID {
	if [ "$PID" != "" ]
	then
		echo "Terminating tmpfs mysqld process with id $PID..."
		sudo kill -s term $PID >>$LOGFILE 2>>$LOGFILE
	fi
}

function initMySQLold {
	echo $MESSAGE_INSTALLING_MYSQL
	sudo mysql_install_db --user=mysql --datadir=/tmp/tmpfs-mysql/datadir >>$LOGFILE 2>>$LOGFILE
	/bin/sleep 1
	echo $MESSAGE_STARTING_MYSQL
	sudo -u mysql mysqld --datadir=/tmp/tmpfs-mysql/datadir --pid-file=/tmp/tmpfs-mysql/tmpfs-mysqld.pid --socket=$SOCKET_FILE --port=$PORT \
	--log-error=/tmp/tmpfs-mysql/error.log --bind-address=0.0.0.0 --innodb_flush_log_at_trx_commit=2 --performance_schema=0 $MYSQLDPARAMS >>$LOGFILE 2>>$LOGFILE &
	/bin/sleep 1
}

function initMySQLnew {
	echo $MESSAGE_INSTALLING_MYSQL
	sudo -u mysql mysqld --initialize-insecure --user=mysql --datadir=/tmp/tmpfs-mysql/datadir >>$LOGFILE 2>>$LOGFILE
	/bin/sleep 1
	echo $MESSAGE_STARTING_MYSQL
	sudo -u mysql mysqld --datadir=/tmp/tmpfs-mysql/datadir --pid-file=/tmp/tmpfs-mysql/tmpfs-mysqld.pid --socket=$SOCKET_FILE --port=$PORT \
	--log-error=/tmp/tmpfs-mysql/error.log --bind-address=0.0.0.0 --innodb_flush_log_at_trx_commit=2 --performance_schema=0 $MYSQLDPARAMS >>$LOGFILE 2>>$LOGFILE &
	/bin/sleep 1
}

function initMariaDB {
	echo $MESSAGE_INSTALLING_MYSQL
	sudo mysql_install_db --user=mysql --datadir=/tmp/tmpfs-mysql/datadir >>$LOGFILE 2>>$LOGFILE
	/bin/sleep 1
	echo $MESSAGE_STARTING_MYSQL
	sudo -u mysql mysqld --datadir=/tmp/tmpfs-mysql/datadir --pid-file=/tmp/tmpfs-mysql/tmpfs-mysqld.pid --socket=$SOCKET_FILE --port=$PORT \
	--log-error=/tmp/tmpfs-mysql/error.log --bind-address=0.0.0.0 --innodb_flush_log_at_trx_commit=2 --performance_schema=0 $MYSQLDPARAMS >>$LOGFILE 2>>$LOGFILE &
  /bin/sleep 1
}

function checkSQLdumpFile {
	if [ "$1" == "" ]; then
		echo -ne "\E[1;33;43mNo database index from the config was specified, assuming 0..."; tput sgr0; echo -ne "\n"
		local CHKDUMPINDEX=0
	else
		local CHKDUMPINDEX=$1
	fi

	if test -e "${DUMPFILES[$CHKDUMPINDEX]}" -a -r "${DUMPFILES[$CHKDUMPINDEX]}" -a -f "${DUMPFILES[$CHKDUMPINDEX]}"
	then
		echo -ne '\E[1;29;42m';
		echo -n "The SQL dump file at '${DUMPFILES[$CHKDUMPINDEX]}' exists and is readable."
		tput sgr0
		echo ""
	else
		echo -ne '\E[1;29;41m';
		echo -n "The SQL dump file at '${DUMPFILES[$CHKDUMPINDEX]}' either does not exists or is not readable."
		tput sgr0
		echo ""
	fi
}

if [ "$1" == "status" ]
then
	if [ "$PID" != "" ]
	then
		echo -n "The tmpfs mysql server seems to be "; echo -ne '\E[1;29;42m'" running "; tput sgr0
	else
		echo -n "The tmpfs mysql server seems to be "; echo -ne '\E[1;29;41m'" down "; tput sgr0
	fi
	echo -e "\n"
	exit 0
fi

function checkStartSuccess {
	local PIDONSTART=`sudo cat /tmp/tmpfs-mysql/tmpfs-mysqld.pid 2>/dev/null`
	if [ "$PIDONSTART" != "" ]
	then
		echo -ne "\E[1;29;42mThe tmpfs mysql server has started"; tput sgr0; echo -ne '\n'
		echo "The password for the tmpfs-mysql server is '$PASSWORD' and the port is '$PORT'."
	else
		echo -ne "\E[1;29;41mThe tmpfs mysql server failed to start "; tput sgr0; echo -ne '\n'
	fi
	echo -ne "\n"
}

if [ "$1" == "client" ]
then
	echo -ne '\E[3;29;44m'"Logging into the tmpfs mysql server..."; tput sgr0
	echo ""
	mysql -u tmpfs --host=0.0.0.0 --port=$PORT --password=$PASSWORD 2>>$LOGFILE
	exit 0
fi

if [ "$1" == "showdb" ]
then
	echo -ne '\E[3;29;44m'"Showing databases on the tmpfs mysql server..."; tput sgr0
	echo ""
	mysql -u tmpfs --host=0.0.0.0 --port=$PORT --password=$PASSWORD -e 'show databases' 2>>$LOGFILE
	echo ""
	exit 0
fi

if [ "$1" == "checkdump" ]
then
	checkSQLdumpFile $2
	echo ""
	exit 0
fi

if [ "$1" == "stop" ]
then
	killByPID
	echo "The tmpfs mysql server instance has been stopped."
	echo ""
	exit 0
fi

if [ "$1" == "kill" ]
then
	killByPID
	MYSQLSERVICEPID=`sudo cat /var/run/mysqld/mysqld.pid 2>/dev/null`
	echo -e "You gave the kill order, we'll now stop the normal mysql server if it is running\n and kill any other instances of the mysqld daemon..."
	if [ "$MYSQLSERVICEPID" != "" ]
	then
		echo "Gracefully stopping the normal mysql server and killing any other mysqld process..."
		sudo service mysql stop >>$LOGFILE 2>>$LOGFILE
		/bin/sleep 1
	fi
	sudo killall mysqld >>$LOGFILE 2>>$LOGFILE
	/bin/sleep 1
	if [ "$MYSQLSERVICEPID" != "" ]
	then
		echo "Starting up the normal mysql server..."
		sudo service mysql restart >>$LOGFILE 2>>$LOGFILE #&
	fi
	exit 0
fi


if [ "$1" == "start" ]
then
	killByPID

	echo "Delete old temporary file system in RAM..."
	sudo umount -l /tmp/tmpfs-mysql >>$LOGFILE 2>>$LOGFILE

	sudo rm -rf /tmp/tmpfs-mysql >>$LOGFILE 2>>$LOGFILE

	echo "Creating temporary file system in RAM..."
	sudo mkdir /tmp/tmpfs-mysql >>$LOGFILE 2>>$LOGFILE
	sudo mount -t tmpfs -o size="$TMPFS_SIZE"M tmpfs /tmp/tmpfs-mysql >>$LOGFILE 2>>$LOGFILE

	sudo chown mysql:mysql /tmp/tmpfs-mysql
	sudo -u mysql mkdir /tmp/tmpfs-mysql/datadir

	if [ "$SERVER_MODE" == 'MariaDB' ]; then
		initMariaDB
	else
		if [ "$MYSQL_VERSION_XX" == "55" -o "$MYSQL_VERSION_XX" == "56" ]; then
			initMySQLold
		fi

		if [ "$MYSQL_VERSION_XX" == "57" -a "${MYSQL_VERSION_xxX}" -lt 6 ]; then
			initMySQLold
		fi

		if [ "$MYSQL_VERSION_Xxx" -ge "5" -a "${MYSQL_VERSION_xXx}" -ge 7 -a "${MYSQL_VERSION_xxX}" -ge 6 ]; then
			initMySQLnew
		fi
	fi

	echo "Waiting for the new mysql server instance to fire up before we continue..."
	/bin/sleep 1

	echo "Set default password and allow access from any host..."

	if [ "$SERVER_MODE" == 'MariaDB' ];
	then
		sudo mysqladmin -u root --host=localhost --port=$PORT --socket=$SOCKET_FILE password $PASSWORD >>$LOGFILE 2>>$LOGFILE
		sudo mysql -u root --host=localhost --port=$PORT --password=$PASSWORD --socket=$SOCKET_FILE -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '$PASSWORD';"
		sudo mysql -u root --host=localhost --port=$PORT --password=$PASSWORD --socket=$SOCKET_FILE -e "CREATE USER 'tmpfs'@'%' IDENTIFIED BY '$PASSWORD';"
		sudo mysql -u root --host=localhost --port=$PORT --password=$PASSWORD --socket=$SOCKET_FILE -e "GRANT ALL PRIVILEGES ON *.* TO 'tmpfs'@'%' IDENTIFIED BY '$PASSWORD';"
		sudo mysql -u root --host=localhost --port=$PORT --password=$PASSWORD --socket=$SOCKET_FILE -e 'FLUSH PRIVILEGES;'
	else
		mysqladmin -u root --host=0.0.0.0 --port=$PORT password $PASSWORD >>$LOGFILE 2>>$LOGFILE
		mysql -u root --host=0.0.0.0 --port=$PORT --password=$PASSWORD -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '$PASSWORD';" >>$LOGFILE 2>>$LOGFILE
		mysql -u root --host=0.0.0.0 --port=$PORT --password=$PASSWORD -e "CREATE USER 'tmpfs'@'%' IDENTIFIED BY '$PASSWORD';"
		mysql -u root --host=0.0.0.0 --port=$PORT --password=$PASSWORD -e "GRANT ALL PRIVILEGES ON *.* TO 'tmpfs'@'%' IDENTIFIED BY '$PASSWORD';"
		mysql -u root --host=0.0.0.0 --port=$PORT --password=$PASSWORD -e 'FLUSH PRIVILEGES;' >>$LOGFILE 2>>$LOGFILE
	fi

	echo

	for DBINDEX in "${!DBNAMES[@]}"
	do
		if [ "${DBNAMES[$DBINDEX]}" != "" ]
		then
			mysql -u tmpfs --host=0.0.0.0 --port=$PORT --password=$PASSWORD -e "create database ${DBNAMES[$DBINDEX]};" >>$LOGFILE 2>>$LOGFILE

			if [ "${DUMPFILES[$DBINDEX]}" != "" ]
			then
				if test -e "${DUMPFILES[$DBINDEX]}" -a -r "${DUMPFILES[$DBINDEX]}" -a -f "${DUMPFILES[$DBINDEX]}"
				then
					echo -ne '\E[1;29;42m';
					echo -n "Importing sql dump file"; tput sgr0
					echo ""
					mysql -u tmpfs --host=0.0.0.0 --port=$PORT --password=$PASSWORD "${DBNAMES[$DBINDEX]}" < "${DUMPFILES[$DBINDEX]}" >>$LOGFILE 2>>$LOGFILE
				else
					echo -ne '\E[1;29;41m';
					echo -n "Couldn't find or read sql dump file, please check the path and try again"; tput sgr0
					echo ""
				fi
			fi

			if [ "${IMPORTSFROM[$DBINDEX]}" != "::::" -a "${IMPORTSFROM[$DBINDEX]}" != "" ]; then
				IMPORT_HOST=`echo "${IMPORTSFROM[$DBINDEX]}" | awk -F":" '{ print $1 }' `
				IMPORT_PORT=`echo "${IMPORTSFROM[$DBINDEX]}" | awk -F":" '{ print $2 }' `
				IMPORT_USER=`echo "${IMPORTSFROM[$DBINDEX]}" | awk -F":" '{ print $3 }' `
				IMPORT_PASS=`echo "${IMPORTSFROM[$DBINDEX]}" | awk -F":" '{ print $4 }' `
				IMPORT_NAME=`echo "${IMPORTSFROM[$DBINDEX]}" | awk -F":" '{ print $5 }' `

				if [ "$IMPORT_HOST" == "" ]; then IMPORT_HOST="127.0.0.1"; fi
				if [ "$IMPORT_PORT" == "" ]; then IMPORT_PORT="3306"; fi
				if [ "$IMPORT_USER" == "" ]; then IMPORT_USER="root"; fi

				if [ "$IMPORT_PASS" != "" -a "$IMPORT_NAME" != "" ]; then
					echo -ne "\E[1;33;45mImporting $IMPORT_NAME database from $IMPORT_HOST"; tput sgr0; echo -ne "\n"
					mysqldump -u "$IMPORT_USER" --password="$IMPORT_PASS" --host="$IMPORT_HOST" --port="$IMPORT_PORT" "$IMPORT_NAME" > "./export.sql" 2>>$LOGFILE
					if test -e "./export.sql" -a -r "./export.sql" -a -f "./export.sql"; then
						mysql -u tmpfs --host=0.0.0.0 --port=$PORT --password=$PASSWORD "${DBNAMES[$DBINDEX]}" < "./export.sql" >>$LOGFILE 2>>$LOGFILE
					fi
					rm -f "./export.sql" >>$LOGFILE 2>>$LOGFILE
				fi

			fi

			if [ "${RUNCOMMANDS[$DBINDEX]}" != "" ]
			then
				echo -ne "\E[1;29;40mExecuting the command configured for database $DBINDEX..."; tput sgr0; echo
				${RUNCOMMANDS[$DBINDEX]} >>$LOGFILE 2>>$LOGFILE
			fi

		fi
	done

	echo
	checkStartSuccess

fi

if test -e "$LOGFILE" -a -r "$LOGFILE" -a -f "$LOGFILE"
then
	cp "$LOGFILE" "$LOGFILE".bak
	tail -n $LOGFILE_LINES "$LOGFILE".bak > "$LOGFILE"
	rm -f "$LOGFILE".bak
fi
